# Generated by Django 2.2.13 on 2020-06-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cvsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvsection',
            name='header',
        ),
        migrations.AddField(
            model_name='cvsection',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvsection',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
