# Generated by Django 2.2.13 on 2020-06-24 00:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200623_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsection',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
