# Generated by Django 2.2.13 on 2020-06-24 00:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200623_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsection',
            name='additional_info',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvsection',
            name='subtitle',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
