# Generated by Django 2.2.13 on 2020-06-24 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200623_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CVSection',
            new_name='Experience',
        ),
    ]
