# Generated by Django 2.2.13 on 2020-06-24 01:10

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200623_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(default='company name', max_length=200),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=tinymce.models.HTMLField(default='sf bay area'),
        ),
        migrations.AddField(
            model_name='experience',
            name='work_period',
            field=tinymce.models.HTMLField(default='date - date'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=tinymce.models.HTMLField(),
        ),
    ]
