# Generated by Django 2.2.13 on 2020-06-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200623_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(default='company', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(default='place, place', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(default='Intern', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='work_period',
            field=models.CharField(default='date - date', max_length=200),
        ),
    ]
