# Generated by Django 2.2.13 on 2020-06-27 03:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Involvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='involvement', max_length=200)),
                ('role', models.CharField(default='member', max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('work_period', models.CharField(default='date - date', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='context',
        ),
    ]
